### PR TITLE
Fix Azure Pipelines

### PR DESCRIPTION
**Pull request by FlameAlt53**

### CODE REVIEW

**Comment by FlameAlt53** [comment]
I think it doesn't know bannertool exists?

**Comment by Epicpkmn11** [comment]
Try running `ls -a` at the end of the `Build TWiLightMenu-Updater` section to see if `bannertool` is in the folder. (I was gonna do it, but it wouldn't let me from Azure)

**Comment by FlameAlt53** [comment]
`ls -a bannertool` ?

**Comment by Epicpkmn11** [comment]
Just do `ls -a`

**Comment by FlameAlt53** [comment]
ah, okay thx

**Comment by FlameAlt53** [comment]
it shows as being in the folder... :/

**Comment by FlameAlt53** [comment]
hmm, it seems that it wants `bannertool` in `bin/sh/` ?

**Comment by Epicpkmn11** [comment]
Try adding `export PATH=$PATH:$(pwd)` to the top of that section

**Comment by FlameAlt53** [comment]
okay

**Comment by FlameAlt53** [comment]
should I perhaps move `makerom` and `bannertool` to `opt/devkitpro/lib/tools`?

**Comment by FlameAlt53** [comment]
wait, that one worked :o

**Comment by FlameAlt53** [comment]
image
i'm getting this on the `succeeded()` line

**Comment by FlameAlt53** [comment]
hmm, do not merge this yet, it seems to get stuck when cloning into `TWLBot/Builds`

**Pull request merged**
